/* Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms. */

// Non-recursive solution

import java.util.*;

public class EvenFibSum {
	public static void main(String[] args) {
		Scanner console = new Scanner(System.in);
		System.out.println("Please specify up until which number of the Fibonacci sequence you would");
		System.out.print("add the even numbers up until: ");
		int num = console.nextInt();
		System.out.println(calculate(num));
	}

	public static int calculate(int x) {
		int a = 1;
		int b = 1;
		int c = 0;
		int result = 0;
		for(int i = 3; i <= x; i++) {
			c = a+b;
			a = b;
			b = c;
			if (c%2 == 0) {
				result += c;
			}
		}
		return result;
	}
}